### PR TITLE
Feature/reconnect

### PR DESCRIPTION
**Pull request by FrankZZ**
Implements proper keepalive

### CODE REVIEW

**Comment by daddvok** [comment]
I apologize for writing here, but I do not know how else to contact you
I saw your improvements and am just experiencing the same problems with  reconnect
I would like to try your improvements, but I can't figure out how to install this build
When i try npm i node-red-contrib-dahua-device or installation from palette, i get original node-red-contrib-dahua 0.0.2
Could you tell me how to install and why you still won't add to palette under your own name? 
You have made very necessary changes, thank you :)

**Comment by FrankZZ** [comment]
@daddvok try running `npm install FrankZZ/node-red-contrib-dahua-device` 
this will instruct npm to retrieve the sources from GitHub instead of the original package on npm

**Comment by FrankZZ** [comment]
I have another PR open to inwaar's repository but it looks like there is no response..

**Comment by daddvok** [comment]
> I have another PR open to inwaar's repository but it looks like there is no response..

I think it is no longer supported and it makes sense to add your repository to node red palette under your name so that more people can use it :)

**Comment by daddvok** [comment]
> @daddvok try running `npm install FrankZZ/node-red-contrib-dahua-device` this will instruct npm to retrieve the sources from GitHub instead of the original package on npm

изображение
изображение

**Comment by daddvok** [comment]
Everything works fine, but for some reason 5 duplicate messages arrive in the debug 
изображение

Also, this error is a little confusing, although in fact everything is fine and as soon as the events appear, everything is connected instantly
изображение

UPD: apparently it was a bug, after the node-red restart, the duplication disappeared

**Pull request merged**
